config/routes.rb
Stocks::Application.routes.draw do
  devise_for :users

  resources :stocks

    root :to => 'stocks#index'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
 
  def self.calculate_average_price_range_count
    all_stocks = Stock.all
    count1 = count2 = count3 = count4 = count5 = count6 = count7 = count8 = count9 = count10 =0
    sum1 = sum2 = sum3 = sum4 = sum5 = sum6 = sum7 = sum8 = sum9 = sum10 = 0
    average1 = average2 = average3 = average4 = average5 = average6 = average7 = average8 = average9 = average10 = 0
    all_stocks.each do |stock|
      case
      when( stock.cost > 0 and stock.cost < 100)
        count1+= 1
        sum1 = sum1 + stock.cost
      when( stock.cost > 101 and stock.cost < 200)
        count2+= 1
        sum2 = sum2 + stock.cost
      when( stock.cost > 201 and stock.cost < 300)
        count3+= 1
        sum3 = sum3 + stock.cost
      when( stock.cost > 301 and stock.cost < 400)
        count4+= 1
        sum4 = sum4 + stock.cost
      when( stock.cost > 401 and stock.cost < 500)
        count5+= 1
        sum5 = sum5 + stock.cost
      when( stock.cost > 501 and stock.cost < 600)
        count6+= 1
        sum6 = sum6 + stock.cost
      when( stock.cost > 601 and stock.cost < 700)
        count7+= 1
        sum7 = sum7 + stock.cost
      when( stock.cost > 701 and stock.cost < 800)
        count8+= 1
        sum8 = sum8 + stock.cost
      when( stock.cost > 801 and stock.cost < 900)
        count9+= 1
        sum9 = sum9 + stock.cost
      when( stock.cost > 901)
        count10+= 1
        sum10 = sum10 + stock.cost
      end
    end
    average1 = (sum1/count1.to_i) unless count1 == 0
    average2 = (sum2/count2.to_i) unless count2 == 0
    average3 = (sum3/count3.to_i) unless count3 == 0
    average4 = (sum4/count4.to_i) unless count4 == 0
    average5 = (sum5/count5.to_i) unless count5 == 0
    average6 = (sum6/count6.to_i) unless count6 == 0
    average7 = (sum7/count7.to_i) unless count7 == 0
    average8 = (sum8/count8.to_i) unless count8 == 0
    average9 = (sum9/count9.to_i) unless count9 == 0
    average10 = (sum10/count10.to_i) unless count10 == 0

    count_in_strings = count10.to_s + "," + count9.to_s + "," + count8.to_s + "," + count7.to_s + "," + count6.to_s + "," + count5.to_s + "," + count4.to_s + "," + count3.to_s + "," + count2.to_s + "," + count1.to_s
    average_in_strings = average10.to_s + "," + average9.to_s + "," + average8.to_s + "," + average7.to_s + "," + average6.to_s + "," + average5.to_s + "," + average4.to_s + "," + average3.to_s + "," + average2.to_s + "," + average1.to_s
    values = {}
    values[:range] =  count_in_strings
    values[:average] =  average_in_strings
    values
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authenticate_user!
  protect_from_forgery
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  # GET /stocks
  # GET /stocks.json
  def index
    if user_signed_in?
      @stocks = Stock.all
      @range_and_average = Stock.calculate_average_price_range_count
      
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @stocks }
      end
    end
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stock = Stock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @stock }
    end
  end

  # GET /stocks/new
  # GET /stocks/new.json
  def new
    @stock = Stock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @stock }
    end
  end

  # GET /stocks/1/edit
  def edit
    @stock = Stock.find(params[:id])
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(params[:stock])

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, :notice => 'Stock was successfully created.' }
        format.json { render :json => @stock, :status => :created, :location => @stock }
      else
        format.html { render :action => "new" }
        format.json { render :json => @stock.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stocks/1
  # PUT /stocks/1.json
  def update
    @stock = Stock.find(params[:id])

    respond_to do |format|
      if @stock.update_attributes(params[:stock])
        format.html { redirect_to @stock, :notice => 'Stock was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @stock.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock = Stock.find(params[:id])
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stocks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<center>
<%= yield %>
</center>
</body>
</html>

app/views/stocks/_datatable.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="display" id="table" width="100%">
<thead>
  <tr>
    <th>Name</th>
    <th>Cost</th>
    <th>Purchase Date</th>
    <th>Purchase Quantity</th>
    <th>Purchase Cost</th>
    <th>Sell Price</th>
    <th>Sell Date</th>
    <th>Sell Quantity</th>
    <th>Sell Cost</th>
    <th>Profit Loss</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
	<% @stocks.each do |stock| %>
  <tr>
    <td><%= link_to "#{stock.name}", stock,{:class => "link-a"} %></td>
    <td><%= stock.cost %></td>
    <td><%= stock.purchase_date %></td>
    <td><%= stock.purchase_quantity %></td>
    <td><%= (stock.purchase_quantity * stock.cost) if(stock.cost and stock.purchase_quantity) %></td>
    <td><%= stock.sell_price %></td>
    <td><%= stock.sell_date %></td>
    <td><%= stock.sell_quantity %></td>
    <td><%#= (stock.sell_quantity * stock.sell_price) if stock.sell_price %></td>
    <td><%= stock.profit_loss %></td>
    <td><%= link_to "Edit", edit_stock_path(stock) %></td>
    <td><%= link_to "Delete", stock, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
	<% end %>
</tbody>
</tfoot>
</table>

app/views/stocks/_form.html.erb
<div style ="background-color: blue,width:600,align:center">
  <%= form_for @stock do |f| %>
    <% if @stock.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

        <ul>
          <% @stock.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field" style="display:block">
      <%= f.label :name %><br />
      <%= f.text_field :name,{:required => true, :class => "ui-widget input ui-state-highlight"} %>
    </div>
    <div class="field" style="display:block">
      <%= f.label :cost %><br />
      <%= f.text_field :cost,{:required => true, :class => "ui-widget input ui-state-highlight"} %>
    </div>
    <div class="field">
      <%= f.label :purchase_date %><br />
      <%= f.text_field :purchase_date,{:required => true, :class => "ui-widget input ui-state-highlight"} %>
    </div>
    <div class="field">
      <%= f.label :purchase_quantity %><br />
      <%= f.text_field :purchase_quantity, {:required => true, :class => "ui-widget input ui-state-highlight"} %>
    </div>
    <div class="field">
      <%= f.label :sell_price %><br />
      <%= f.text_field :sell_price,{:class => "ui-widget input ui-state-highlight"} %>
    </div>
    <div class="field">
      <%= f.label :sell_date %><br />
      <%= f.text_field :sell_date,{ :class => "ui-widget input ui-state-highlight"} %>
    </div>
    <div class="field">
      <%= f.label :sell_quantity %><br />
      <%= f.text_field :sell_quantity,{ :class => "ui-widget input ui-state-highlight"} %>
    </div>
    <div class="field">
      <%= f.label :profit_loss %><br />
      <%= f.text_field :profit_loss,{ :class => "ui-widget input ui-state-highlight"} %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/_highcharts.html.erb
<script type="text/javascript">
  var chart;
  $(document).ready(function() {
    var chart1; // globally available
    $(document).ready(function() {
      chart1 = new Highcharts.Chart({
        chart: {
          renderTo: 'container',
          type: 'bar'
        },
        title: {
          text: 'Stock Ranges'
        },
        xAxis: {
          categories: ['Above Rs 900','800-900','700-800','600-700', '500-600','400-500','300-400','200-300', '100-200', '0-100']
        },
        yAxis: {
          title: {
            text: 'Number of Stocks'
          }
        },
        series: [{
            name: 'Count',
            data: [<%= @range_and_average[:range] %>]
          },{
            name: 'Average Price',
            data: [<%= @range_and_average[:average] %>]
          }
          ]
      });
    });
  });

</script>
</head>

<body>

  <div id="container" style="width: 800px; height: 400px; margin: 0 auto"></div>

</body>
</html>

app/views/stocks/_jqgrid.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="display" id="table-jqgrid" width="100%">

</table>



<script>
jQuery("#table-jqgrid").jqGrid({
	datatype: "local",
 	height: 250,
	width: 900,
        rowNum:3,
        rowList:[2,4,8],
        sortname: 'cost',
        viewrecords: true,
        sortorder: "desc",
        loadonce: true,
        caption: "Stocks Details",
	colNames:['Name','Cost', 'Purchase Date', 'Purchase Quantity','Purchase Cost'],
	colModel:[
		{name:'name',index:'name', width:100},
		{name:'cost',index:'cost', width:70, sorttype:"float"},
		{name:'pdate',index:'pdate', width:100, sorttype:"date"},
		{name:'pqty',index:'pqty', width:80, align:"right",sorttype:"int"},
		{name:'pcost',index:'pcost', width:80, align:"right",sorttype:"float"}
		],
	toppager: true,
	rowList: [5,10],
	multiselect: false,
	altRows: true,
	caption: "Stocks" });

var mydata = [
  <% @stocks.each do |stock| %>
    {
	name: "<%= stock.name %>",
	cost: "<%= stock.cost %>",
	pdate: "<%=stock.purchase_date %>",
	pqty:"<%= stock.purchase_quantity %>",
	pcost:"<%= (stock.purchase_quantity * stock.cost)  %>"
    },
	<% end %>
	    ];

for(var i=0;i<=mydata.length;i++) jQuery("#table-jqgrid").jqGrid('addRowData',i+1,mydata[i]);

</script>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<marquee class="ui-state-error ui-corner-all">THIS PORTAL IS UNDER DEVELOPMENT for any queries please connect to :  ashish.upadhyaye@gmail.com </marquee>
<span style = "float:right">
  <%= link_to 'New Stock', new_stock_path, {:class => "ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"} %></span>
<br />
<br />
<html>
  <head>
    <script>

    </script>
  </head>
  <body>
    <div class="main">
      <div id="tabs">
        <ul>
          <li><a href="#tabs-1">DataTables</a></li>
          <li><a href="#tabs-2">JQgrid</a></li>
          <li><a href="#tabs-3">High Charts</a></li>
        </ul>
        <div id="tabs-1">
          <%= render :partial => 'datatable' %>
        </div>
        <div id="tabs-2">
          <%= render :partial => 'jqgrid' %>
        </div>
        <div id="tabs-3">
          <%= render :partial => 'highcharts' %>
        </div>
      </div><!----tabs closed-->
    </div>
  </body>
</html>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @stock.name %>
</p>

<p>
  <b>Cost:</b>
  <%= @stock.cost %>
</p>

<p>
  <b>Purchase date:</b>
  <%= @stock.purchase_date %>
</p>

<p>
  <b>Purchase Quantity:</b>
  <%= @stock.purchase_quantity %>
</p>

<p>
  <b>Sell price:</b>
  <%= @stock.sell_price %>
</p>

<p>
  <b>Sell date:</b>
  <%= @stock.sell_date %>
</p>

<p>
  <b>Sell Quantity:</b>
  <%= @stock.sell_quantity %>
</p>

<p>
  <b>Profit loss:</b>
  <%= @stock.profit_loss %>
</p>


<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>